# Generated by Django 4.2.5 on 2023-09-29 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('StockMaster_app', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idproducts', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('precio', models.PositiveBigIntegerField()),
                ('marca', models.CharField(max_length=255)),
                ('cantPro', models.CharField(max_length=255)),
                ('imagen', models.BinaryField(blank=True, null=True)),
            ],
        ),
    ]
