# Generated by Django 4.2.5 on 2023-09-30 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensajes',
            fields=[
                ('idcomentario', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=255)),
                ('nusuario', models.CharField(max_length=255)),
            ],
        ),
    ]
