# Generated by Django 4.2.5 on 2023-10-01 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0007_alter_mensajes_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensajes',
            name='username',
            field=models.CharField(max_length=255),
        ),
    ]
